# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"x\n\x04user\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\x12\x17\n\x08usertype\x18\x06 \x01(\x0e\x32\x05.Type\x12\x18\n\x04type\x18\x07 \x01(\x0e\x32\n.Operation*\x1f\n\x04Type\x12\x0c\n\x08\x43USTOMER\x10\x00\x12\t\n\x05\x41\x44MIN\x10\x01*O\n\tOperation\x12\n\n\x06UNKWON\x10\x00\x12\n\n\x06\x43REATE\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\x12\n\x0eUPDATEPASSWORD\x10\x03\x12\n\n\x06\x44\x45LETE\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TYPE._serialized_start=136
  _TYPE._serialized_end=167
  _OPERATION._serialized_start=169
  _OPERATION._serialized_end=248
  _USER._serialized_start=14
  _USER._serialized_end=134
# @@protoc_insertion_point(module_scope)
